package entity;
// Generated 26.04.2016 22:20:35 by Hibernate Tools 4.3.1


/**
 * User generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String password;

    public Admin() {
    }

	
    public Admin(String email, String password) {
        this.email = email;
        this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
}


