package entity;
// Generated 26.04.2016 22:20:35 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private Integer id;
     private Integer sectionId;
     private String title;
     private String description;
     private String preview;
     private int numberOfPages;
     private int price;
     private String fileName;
     private String author;
     private int year;
     private Date dateOfPublicaion;
     private String image;

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public Book() {
    }

	
    public Book(Integer sectionId, String title, String description, String preview, int numberOfPages, int price, String fileName, String author, int year, Date dateOfPublicaion, String image) {
        this.sectionId = sectionId;
        this.title = title;
        this.description = description;
        this.preview = preview;
        this.numberOfPages = numberOfPages;
        this.price = price;
        this.fileName = fileName;
        this.author = author;
        this.year = year;
        this.dateOfPublicaion = dateOfPublicaion;
        this.image = image;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getSection() {
        return this.sectionId;
    }
    
    public void setSection(Integer sectionId) {
        this.sectionId = sectionId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getPreview() {
        return this.preview;
    }
    
    public void setPreview(String preview) {
        this.preview = preview;
    }
    public int getNumberOfPages() {
        return this.numberOfPages;
    }
    
    public void setNumberOfPages(int numberOfPages) {
        this.numberOfPages = numberOfPages;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }
    public Date getDateOfPublicaion() {
        return this.dateOfPublicaion;
    }
    
    public void setDateOfPublicaion(Date dateOfPublicaion) {
        this.dateOfPublicaion = dateOfPublicaion;
    }




}


