package entity;
// Generated 26.04.2016 22:20:35 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private Integer id;
     private Integer book;
     private Integer user;
     private String content;
     private Date date;

    public Comment() {
    }

    public Comment(Integer book, Integer user, String content, Date date) {
       this.book = book;
       this.user = user;
       this.content = content;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getBook() {
        return this.book;
    }
    
    public void setBook(Integer book) {
        this.book = book;
    }
    public Integer getUser() {
        return this.user;
    }
    
    public void setUser(Integer user) {
        this.user = user;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


