package entity;
// Generated 26.04.2016 22:20:35 by Hibernate Tools 4.3.1



/**
 * Purchase generated by hbm2java
 */
public class Purchase  implements java.io.Serializable {


     private Integer id;
     private Integer book;
     private Integer user;
     private String cardNumber;
     private String securityNumber;
     private String firstName;
     private String secondName;
     private String country;

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getSecondName() {
        return secondName;
    }

    public void setSecondName(String secondName) {
        this.secondName = secondName;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public Purchase() {
    }

    public Purchase(Integer book, Integer user, String cardNumber, String securityNumber, String firstName, String secondName, String country) {
       this.book = book;
       this.user = user;
       this.cardNumber = cardNumber;
       this.securityNumber = securityNumber;
       this.firstName = firstName;
       this.secondName = secondName;
       this.country = country;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getBook() {
        return this.book;
    }
    
    public void setBook(Integer book) {
        this.book = book;
    }
    public Integer getUser() {
        return this.user;
    }
    
    public void setUser(Integer user) {
        this.user = user;
    }
    public String getCardNumber() {
        return this.cardNumber;
    }
    
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }
    public String getSecurityNumber() {
        return this.securityNumber;
    }
    
    public void setSecurityNumber(String securityNumber) {
        this.securityNumber = securityNumber;
    }




}


