package entity;
// Generated 26.04.2016 22:20:35 by Hibernate Tools 4.3.1



/**
 * Rating generated by hbm2java
 */
public class Rating  implements java.io.Serializable {


     private Integer id;
     private Integer book;
     private Integer user;
     private int value;

    public Rating() {
    }

    public Rating(Integer book, Integer user, int value) {
       this.book = book;
       this.user = user;
       this.value = value;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getBook() {
        return this.book;
    }
    
    public void setBook(Integer book) {
        this.book = book;
    }
    public Integer getUser() {
        return this.user;
    }
    
    public void setUser(Integer user) {
        this.user = user;
    }
    public int getValue() {
        return this.value;
    }
    
    public void setValue(int value) {
        this.value = value;
    }




}


