package entity;
// Generated 26.04.2016 22:20:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Section generated by hbm2java
 */
public class Section  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private String image;

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public Section() {
    }

	
    public Section(String name, String description, String image) {
        this.name = name;
        this.description = description;
        this.image = image;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
}


